# 1) Hyperplanes

We will be using the notion of a hyperplane a great deal. A hyperplane is useful for classification, as discussed in the notes.
<img src="example1.png" width="500" height="500">

Some notational conventions:

x: is a point in d-dimensional space (represented as a column vector of d real numbers), R^d
d

θ: a point in d-dimensional space (represented as a column vector of d real numbers), R^dR
d

θ0: a single real number

We represent x and θ as column vectors, that is, d×1 arrays. Remember dot products? We write dot products in one of two ways: θ^T x or θ⋅.x. In both cases:

<br />
<center>
θ^ 
T
 x=θ⋅x=θ 
1
​
 x 
1
​
 +θ 
2
​
 x 
2
​
 +…+θ 
d
​
 x 
d
​
</center>
<br />

In a dd-dimensional space, a hyperplane is a d-1d−1 dimensional subspace that can be characterized by a normal to the subspace and a scalar offset. For example, any line is a hyperplane in two dimensions, an infinite flat sheet is a hyperplane in three dimensions, but in higher dimensions, hyperplanes are harder to visualize. Fortunately, they are easy to specify.

Hint: When doing the two-dimensional problems below, start by drawing a picture. That should help your intuition. If you get stuck, take a look at this geometry review for planes and hyperplanes.

## 1.1) Through origin

In dd dimensions, any vector \theta \in R^dθ∈R 
d
  can define a hyperplane. Specifically, the hyperplane through the origin associated with \thetaθ is the set of all vectors x \in R^dx∈R 
d
  such that \theta^T x = 0θ 
T
 x=0. Note that this hyperplane includes the origin, since x=0x=0 is in the set.
 
 <img src="example1-labelled.png" width="500" height="500">
 
 Ex1.1a: In two dimensions, \theta = [\theta_1, \theta_2]θ=[θ 
1
​
 ,θ 
2
​
 ] can define a hyperplane. Let \theta = [1, 2]θ=[1,2]. Give a vector that lies on the hyperplane given by the set of all x \in R^2x∈R 
2
  such that \theta^T x = 0θ 
T
 x=0:
 
 Enter your answer as a Python list of numbers.

In [3]:
print([0,0])

[0, 0]


Ex1.1b. Using the same hyperplane, determine a vector that is normal to the hyperplane.

In [4]:
print([1,2])

[1, 2]


Ex1.1c. Now, in dd dimensions, supply the simplified formula for a unit vector normal to the hyperplane in terms of \thetaθ where \theta \in R^dθ∈R 
d
 .

In this question and the subsequent ones that ask for a formula, enter your answer as a Python expression. Use theta for \thetaθ, theta_0 for \theta_0θ 
0
​
 , x for any array x,x, transpose(x) for transpose of an array, norm(x) for the length (L2-norm) of a vector, and x@y to indicate a matrix product of two arrays.

In [6]:
print("-theta/((transpose(theta)@theta)**.5)")

-theta/((transpose(theta)@theta)**.5)


## 1.2) General hyperplane, distance to origin

Now, we'll consider hyperplanes defined by \theta^T x + \theta_0 = 0θ 
T
 x+θ 
0
​
 =0, which do not necessarily go through the origin. Distances from points to such general hyperplanes are useful in machine learning models, such as the perceptron (as described in the notes).

Define the positive side of a hyperplane to be the half-space defined by \{x \mid \theta^T x + \theta_0 &gt; 0\}{x∣θ 
T
 x+θ 
0
​>0}, so \thetaθ points toward the positive side.

 <img src="example2.png" width="500" height="500">

Ex1.2a. In two dimensions, let \theta = [3, 4]θ=[3,4] and \theta_0 = 5θ 
0
​
 =5. What is the signed perpendicular distance from the hyperplane to the origin? The distance should be positive if the origin is on the positive side of the hyperplane, 0 on the hyperplane and negative otherwise. It may be helpful to draw your own picture of the hyperplane (like the one above but with the right intercepts and slopes) with \theta = [3, 4]θ=[3,4] and \theta_0 = 5θ 
0
​
 =5. Hint -Draw a picture

In [9]:
print(1) #the distance from the origin to the hyperplane

1


Ex1.2b: Now, in dd dimensions, supply the formula for the signed perpendicular distance from a hyperplane specified by \theta, \theta_0θ,θ 
0
​
  to the origin. If you get stuck, take a look at this walkthrough of point-plane distances.

In [11]:
print("theta_0 / norm(theta)")

theta_0 / norm(theta)


# 2) Numpy intro

numpy is a package for doing a variety of numerical computations in Python. We will use it extensively. It supports writing very compact and efficient code for handling arrays of data. We will start every code file that uses numpy with import numpy as np, so that we can reference numpy functions with the 'np.' precedent.

You can find general documentation on numpy here, and we also have a 6.036-specific numpy tutorial.

The fundamental data type in numpy is the multidimensional array, and arrays are usually generated from a nested list of values using the np.array command. Every array has a shape attribute which is a tuple of dimension sizes.

In this class, we will use two-dimensional arrays almost exclusively. That is, we will use 2D arrays to represent both matrices and vectors! This is one of several times where we will seem to be unnecessarily fussy about how we construct and manipulate vectors and matrices, but we have our reasons. We have found that using this format results in predictable results from numpy operations.

Using 2D arrays for matrices is clear enough, but what about column and row vectors? We will represent a column vector as a d\times 1d×1 array and a row vector as a 1\times d1×d array. So for example, we will represent the three-element column vector,

x = \begin{bmatrix}1 \\ 5 \\ 3\end{bmatrix},

as a 3 \times 13×1 numpy array. This array can be generated with
~~~    x = np.array([[1],[5],[3]]),

or by using the transpose of a 1 \times 31×3 array (a row vector) as in,

~~~    x = np.transpose(np.array([[1,5,3]]),

where you should take note of the "double" brackets.

It is often more convenient to use the array attribute .T , as in

~~~    x = np.array([[1,5,3]]).T

to compute the transpose.

Before you begin, we would like to note that in this assignment we will not accept answers that use "loops". One reason for avoiding loops is efficiency. For many operations, numpy calls a compiled library written in C, and the library is far faster than that interpreted Python (in part due to the low-level nature of C, optimizations like vectorization, and in some cases, parallelization). But the more important reason for avoiding loops is that using higher-level constructs leads to simpler code that is easier to debug. So, we expect that you should be able to transform loop operations into equivalent operations on numpy arrays, and we will practice this in this assignment.

Of course, there will be more complex algorithms that require loops, but when manipulating matrices you should always look for a solution without loops.

Numpy functions and features you should be familiar with for this assignment:

np.array
np.transpose (and the equivalent method a.T)
np.ndarray.shape
np.dot (and the equivalent method a.dot(b) )
np.sign
np.sum (look at the axis and keepdims arguments)
Elementwise operators +, -, *, /
Note that in Python, np.dot(a, b) is the matrix product a@b, not the dot product a^T ba 
T
 b.

## 2.1) Array

Provide an expression that sets A to be a 2 \times 32×3 numpy array (22 rows by 33 columns), containing any values you wish.

In [14]:
import numpy as np
A = np.array([[2, 4, 6], [6, 8, 10]], np.int32)

print(A)

[[ 2  4  6]
 [ 6  8 10]]


## 2.2) Transpose

Write a procedure that takes an array and returns the transpose of the array. You can use 'np.transpose' or the '.T', but you may not use a loop.

In [17]:
import numpy as np
def tp(A):
    return np.transpose(A)

print(tp([[1,2,3],[4,5,6]]))

[[1 4]
 [2 5]
 [3 6]]


## 2.3) Shapes

Let A be a 4\times 24×2 numpy array, B be a 4\times 34×3 array, and C be a 4\times 14×1 array. For each of the following expressions, indicate the shape of the result as a tuple of integers (recall python tuples use parentheses, not square brackets, which are for lists, and a tuple of a single object x is written as (x,) with a comma) or "none" (as a Python string with quotes) if it is illegal.

Ex2.3a (c*c)

In [20]:
import numpy as np

first_four_by_one = np.array([[1], [2], [3], [4]])
print(first_four_by_one.shape)

second_four_by_one = np.array([[4], [5], [6], [7]])
print(second_four_by_one.shape)

result = first_four_by_one * second_four_by_one
print(result.shape)
print(result)

(4, 1)
(4, 1)
(4, 1)
[[ 4]
 [10]
 [18]
 [28]]


Ex2.3b (np.dot(C, C))

In [34]:
import numpy as np

c = np.array([[1], [2], [3], [4]])
# print(np.dot(c,c))

# print(np.dot(c,c).shape)

print("The result is error, should be answer as 'none'")

The result is error, should be answer as 'none'


Ex2.3c (np.dot(np.transpose(C), C))

In [33]:
import numpy as np

c = np.array([[1], [2], [3], [4]])
print(np.dot(np.transpose(c), c))

print(np.dot(np.transpose(c), c).shape)

[[30]]
(1, 1)


Ex2.3d (np.dot(A, B))

In [44]:
import numpy as np

a = np.array([[1,2,3,4], [2,2,3,4]])
b = np.array([[1,2,3,4], [2,2,3,4], [2,2,3,4]])
# print(np.dot(c,c))

# print(np.dot(c,c).shape)

print("The result is error, should be answer as 'none'")

The result is error, should be answer as 'none'


Ex2.3e (np.dot(A.T, B))

In [46]:
import numpy as np

a = np.array([[1,2,3,4], [2,2,3,4]])
b = np.array([[1,2,3,4], [2,2,3,4], [2,2,3,4]])

# print(np.dot(np.transpose(a), b))

# print(np.dot(a,b).shape)

print("The result is error, should be answer as 'none'. But the correct result is (2,3)")

The result is error, should be answer as 'none'. But the correct result is (2,3)


Ex2.3f (D = np.array([1,2,3]))

In [50]:
import numpy as np

D = np.array([1,2,3])

print(D)

print("The result should be (3, )")

[1 2 3]
The result should be (3, )


Ex2.3g (A[:,1])

In [58]:
import numpy as np

a = np.array([[1,2,3,4], [2,2,3,4], [1,2,3,4], [1,2,3,4]])

print(a[:,1])
print(a[:,1].shape)

[2 2 2 2]
(4,)


Ex2.3h (A[:,1:2])

In [59]:
import numpy as np

a = np.array([[1,2,3,4], [2,2,3,4], [1,2,3,4], [1,2,3,4]])

print(a[:,1:2])
print(a[:,1:2].shape)

[[2]
 [2]
 [2]
 [2]]
(4, 1)


## 2.4) Row vector

Write a procedure that takes a list of numbers and returns a 2D numpy array representing a row vector containing those numbers.

In [63]:
import numpy as np
def rv(value_list):
    return np.array([value_list])

print(rv([[1,2,3,4], [2,2,3,4], [1,2,3,4], [1,2,3,4]]))

[[[1 2 3 4]
  [2 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


## 2.5) Column vector

Write a procedure that takes a list of numbers and returns a 2D numpy array representing a column vector containing those numbers. You can use the rv procedure.



In [65]:
import numpy as np
def cv(value_list):
    return np.transpose(np.array([value_list]))

print(cv([[1,2,3,4], [2,2,3,4], [1,2,3,4], [1,2,3,4]]))

[[[1]
  [2]
  [1]
  [1]]

 [[2]
  [2]
  [2]
  [2]]

 [[3]
  [3]
  [3]
  [3]]

 [[4]
  [4]
  [4]
  [4]]]


## 2.6) length

Write a procedure that takes a column vector and returns the vector's Euclidean length (or equivalently, its magnitude) as a scalar. You may not use np.linalg.norm, and you may not use a loop.

In [66]:
import numpy as np
def length(col_v):
    return np.sqrt(np.sum(np.square([col_v])))

print(length([[1,2,3,4], [2,2,3,4], [1,2,3,4], [1,2,3,4]]))

11.090536506409418


## 2.7) normalize

Write a procedure that takes a column vector and returns a unit vector in the same direction. You may not use a for loop. Use your length procedure from above (you do not need to define it again).

In [67]:
import numpy as np
def normalize(col_v):
    return col_v / np.linalg.norm(col_v)

print(normalize([[1,2,3,4], [2,2,3,4], [1,2,3,4], [1,2,3,4]]))

[[0.09016696 0.18033393 0.27050089 0.36066785]
 [0.18033393 0.18033393 0.27050089 0.36066785]
 [0.09016696 0.18033393 0.27050089 0.36066785]
 [0.09016696 0.18033393 0.27050089 0.36066785]]


## 2.8) indexing

Write a procedure that takes a 2D array and returns the final column as a two dimensional array. You may not use a for loop.

In [77]:
import numpy as np
def index_final_col(A):
    flipped_array = np.flip(A, 1)
    return flipped_array[:,:1]

print(index_final_col([[1,2],[3,4]]))

[[2]
 [4]]


## 2.9) Representing data

Alice has collected weight and height data of 3 people and has written it down below:
Weight, height

150, 5.8

130, 5.5

120, 5.3

She wants to put this into a numpy array such that each row represents one individual's height and weight in the order listed. Write code to set data equal to the appropriate numpy array:

In [79]:
import numpy as np
data = np.array([[150, 5.8], [130, 5.5], [120, 5.3]])

print(data)

[[150.    5.8]
 [130.    5.5]
 [120.    5.3]]


Now she wants to compute the sum of each person's height and weight as a column vector by multiplying data by another numpy array. She has written the following incorrect code to do so and needs your help to fix it:

## 2.10) Matrix multiplication


In [81]:
import numpy as np
def transform(data):
    return (np.dot(data, np.array([[1], [1]])))

print(transform([[150, 5.8], [130, 5.5], [120, 5.3]]))

[[155.8]
 [135.5]
 [125.3]]
